# Generated by Django 4.0.3 on 2022-05-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruser', models.CharField(max_length=50)),
                ('rname', models.CharField(max_length=50)),
                ('rmail', models.CharField(max_length=50)),
                ('rcontact', models.CharField(max_length=50)),
                ('rpass', models.CharField(max_length=50)),
            ],
        ),
    ]
