# Generated by Django 4.0.3 on 2022-05-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='guest_entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=50)),
                ('guest_num', models.CharField(max_length=50)),
                ('guest_id', models.CharField(max_length=50)),
                ('guest_room', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('intime', models.CharField(max_length=50)),
                ('exittime', models.CharField(max_length=50)),
            ],
        ),
    ]
