# Generated by Django 4.0.3 on 2022-05-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='manager_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muser', models.CharField(max_length=50)),
                ('mpass', models.CharField(max_length=50)),
            ],
        ),
    ]
